version: 2.1
jobs:
  sonarcloud:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            curl -sSLo sonarqube-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonarqube-scanner-cli.zip
            ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.organization=your_organization_key -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN
workflows:
  version: 2
  build:
    jobs:
      - sonarcloud
